version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    nuget-non-major:
      applies-to: version-updates
      patterns:
        - "*"
      update-types:
        - minor
        - patch
